/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class SiftDocument {
  /** Detected file type. */
  get fileType(): FileType
  /** All metadata tags. */
  tags(): Array<Tag>
  /** GPS coordinates, or null if not present. */
  gps(): GpsCoordinates | null
  /** EXIF thumbnail bytes (JPEG), or null. */
  thumbnail(): Buffer | null
  /** Extracted PDF images. */
  images(): Array<ExtractedImage>
  /** Text per PDF page. */
  textPages(): Array<string>
  /** EXIF tags only. */
  exifTags(): Array<Tag>
  /** XMP tags only. */
  xmpTags(): Array<Tag>
  /** IPTC tags only. */
  iptcTags(): Array<Tag>
  /** Raw text per PDF page (no layout). */
  textPagesRaw(): Array<string>
  /** Authenticate encrypted PDF. Returns true if password accepted. */
  authenticate(password: Buffer): boolean
  /** PDF form fields, or null if no form. */
  acroForm(): AcroFormData | null
  /** All PDF annotations. */
  annotations(): Array<Annotation>
  /** Tagged PDF structure tree, or null if not tagged. */
  structTree(): StructTreeData | null
  /** Release native resources. */
  close(): void
}

export declare class SiftFile {
  /** Open a file by path (memory-mapped). */
  static open(path: string): SiftFile
  /** Detected file type. */
  get fileType(): FileType
  /** Parse into a SiftDocument. */
  parse(): SiftDocument
  /** Release the memory mapping. */
  close(): void
}

export interface AcroFormData {
  fields: Array<FormField>
  needAppearances: boolean
  sigFlags: number
  totalFieldCount: number
}

export interface Annotation {
  annotType: string
  page: number
  rect: Array<number>
  contents?: string
  dest?: string
  name?: string
  modified?: string
  flags: number
  hasAppearance: boolean
}

export interface ExtractedImage {
  page: number
  width: number
  height: number
  bitsPerComponent: number
  components: number
  format: ImageFormat
  data: Buffer
  extension: string
  isPassthrough: boolean
}

export declare const enum FileType {
  Unknown = 0,
  Jpeg = 1,
  Png = 2,
  Gif = 3,
  Bmp = 4,
  Tiff = 5,
  WebP = 6,
  Heif = 7,
  Pdf = 8,
  Icc = 9,
  QuickTime = 10
}

export interface FormField {
  fieldType: string
  name: string
  value?: string
  defaultValue?: string
  flags: number
  isReadOnly: boolean
  isRequired: boolean
  options: Array<string>
  children: Array<FormField>
}

export interface GpsCoordinates {
  latitude: number
  longitude: number
  /** Meters above sea level, or null if unavailable. */
  altitude?: number
}

export declare const enum ImageFormat {
  Jpeg = 0,
  Jpeg2000 = 1,
  Jbig2 = 2,
  Ccitt = 3,
  Pixels = 4
}

/** Parse a document from a Buffer. */
export declare function read(data: Buffer): SiftDocument

export interface RoleMapEntry {
  custom: string
  standard: string
}

export interface StructChildData {
  /** "element", "content_ref", or "object_ref" */
  childType: string
  element?: StructElementData
  mcid?: number
  objNum?: number
}

export interface StructElementData {
  structType: string
  title?: string
  altText?: string
  actualText?: string
  lang?: string
  children: Array<StructChildData>
}

export interface StructTreeData {
  rootElements: Array<StructElementData>
  roleMap: Array<RoleMapEntry>
}

export interface Tag {
  group: string
  name: string
  value: string
}

/** Extract tags from a file path in one call. */
export declare function tags(path: string): Array<Tag>

/** Native library version. */
export declare function version(): string
